[command]
default=cmew-esmvaltool-env aa_create_page \
       = --title "$ASSESSMENT_TITLE"       \
       = --area $AREA                      \
       = --ref-suite-id $REF_SUITE_ID      \
       = --exp-suite-id $SUITE_ID          \
       = --start-date $START_DATE          \
       = --end-date $END_DATE > ${AUTOASSESS_OUTPUT_DIR}/${AREA}.html
