# (C) Crown Copyright 2022-2026, Met Office.
# The LICENSE.md file contains full licensing details.

[file:cmip6_datasets.nl]
source=(namelist:cmip6_datasets(:))

[file:model_runs.nl]
source=(namelist:model_runs(:))

[namelist:cmip6_datasets(1)]
experiment_id="historical"
grid="gn"
institute="CSIRO-ARCCSS"
label_for_plots="CMIP6_ACCESS-CM2"
model_id="ACCESS-CM2"
variant_label="r1i1p1f1"

[namelist:model_runs(1)]
calendar="360_day"
experiment_id="historical"
label_for_plots="UKESM1.0 N96ORCA1"
model_id="UKESM1-0-LL"
suite_id="u-az513"
variant_label="r1i1p1f1"

[namelist:model_runs(reference)]
calendar="360_day"
experiment_id="historical"
label_for_plots="HadGEM3-GC3.1 N96ORCA1"
model_id="HadGEM3-GC31-LL"
suite_id="u-bv526"
variant_label="r5i1p1f3"

[namelist:model_runs(test)]
calendar="gregorian"
experiment_id="amip"
label_for_plots="HadGEM3-GC5E-LL N96ORCA1"
model_id="HadGEM3-GC5E-LL"
suite_id="u-cw673"
variant_label="r1i1p1f1"

[template variables]
AUTOASSESS=false
!!AUTOASSESS_TITLE=""
MAX_PARALLEL_TASKS=4
NUMBER_OF_YEARS=2
!!RAW_DATA_DIR=""
RAW_DATA_DIR_MODE="off"
START_YEAR=1993
TEST=false
UNITTEST=false
