[file:cmip6_datasets.nl]
source=(namelist:cmip6_datasets(:))

[file:model_runs.nl]
source=(namelist:model_runs(:))

[namelist:model_runs(cmm1)]
calendar="360_day"
experiment_id="amip"
label_for_plots="u-ds902/CH4-jules scaling"
model_id="UKESM1-0-LL"
suite_id="u-ds902"
variant_label="r1i1p1f1"

[namelist:model_runs(reference)]
calendar="360_day"
experiment_id="amip"
label_for_plots="u-dr725/UKESM1p3+C7 volc+solar+CH4+GHG"
model_id="UKESM1-0-LL"
suite_id="u-dr725"
variant_label="r5i1p1f3"

[template variables]
AUTOASSESS=false
!!AUTOASSESS_TITLE=""
!!ESMVALTOOL_BRANCH="main"
LABEL_FOR_PLOTS="UKESM1-0-LL"
MAX_PARALLEL_TASKS=20
NUMBER_OF_YEARS=5
!!RAW_DATA_DIR=""
RAW_DATA_DIR_MODE="off"
START_YEAR=3150
SUITE_ID="u-dq123"
# START_YEAR=1993
TEST=false
UNITTEST=false
USE_ESMVALTOOL_BRANCH=false
