# (C) Crown Copyright 2022-2026, Met Office.
# The LICENSE.md file contains full licensing details.

[command]
default=cmew-esmvaltool-env configure_recipe \
       =--cmew_data_for_esmval_dir $CMEW_DATA_FOR_ESMVAL_DIR \
       =--dev_config_path $DEV_CONFIG_PATH \
       =--drs_cmip6 $DRS_CMIP6 \
       =--drs_obs4mips $DRS_OBS4MIPS \
       =--max_parallel_tasks $MAX_PARALLEL_TASKS \
       =--mip_table_dir $MIP_TABLE_DIR \
       =--output_dir $OUTPUT_DIR \
       =--rootpath_cmip6 $ROOTPATH_CMIP6 \
       =--rootpath_obs4mips $ROOTPATH_OBS4MIPS \
       =--user_config_path $USER_CONFIG_PATH
