[command]
default=cmew-esmvaltool-env aa_mjo                    \
       = --area $AREA                                 \
       = --exp-suite-id $REF_SUITE_ID $SUITE_ID       \
       = --exp-desc '$REF_SUITE_TITLE' '$SUITE_TITLE' \
       = --ref-suite-id $REF_SUITE_ID                 \
       = --out-dir $AUTOASSESS_OUTPUT_DIR/$AREA       \
       = --data-dir $AUTOASSESS_DATA_DIR              \
       = --start-date $START_DATE                     \
       = --end-date $END_DATE                         \
       = --obs-dir $OBS_CLIM_PATH                     \
       = --tmp-dir $CYLC_TASK_WORK_DIR                \
       = --ancil-dir $ANCIL_PATH                      \
       = --ncpu 1
