# (C) Crown Copyright 2024-2026, Met Office.
# The LICENSE.md file contains full licensing details.
[project]
name = "cmewpy"
dynamic = ["version"]

[project.scripts]
add_datasets_to_share = "cmewpy.copy_datasets.add_datasets_to_share:main"
configure_recipe = "cmewpy.configure_recipe.configure_recipe:main"
create_request_file = "cmewpy.configure_standardise.create_request_file:main"
create_variables_file = "cmewpy.configure_standardise.create_variables_file:main"
fetch_recipe = "cmewpy.configure_for.fetch_recipe:main"
get_output_variables = "cmewpy.configure_for.output_variables:main"
update_recipe_file = "cmewpy.configure_for.update_recipe_file:main"

[build-system]
requires = ["setuptools >= 80.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["etc*"]

# Configure black.
[tool.black]
line-length = 79
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | build
    | dist
  )/
)
'''

# Configure pytest.
[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
filterwarnings = [
    # Ignore deprecation warnings from webob, esmpy and pkg_resources:
    "ignore:'cgi' is deprecated and slated for removal in Python 3.13:DeprecationWarning",
    "ignore:Implicit None on return values is deprecated:DeprecationWarning",
    "ignore:Deprecated call to `pkg_resources.declare_namespace:DeprecationWarning",
    # Ignore user warnings from pybtex:
    "ignore:pkg_resources is deprecated as an API:UserWarning",
]
