# (C) Crown Copyright 2022-2025, Met Office.
# The LICENSE.md file contains full licensing details.

# See https://pre-commit.com for more information.
# See https://pre-commit.com/hooks.html for more hooks.
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files

    # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
    -   id: black
        # Force black to run on whole repo, using settings from pyproject.toml
        pass_filenames: false
        always_run: true
        args: [--config=./pyproject.toml, .]
        # Black uses pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        always_run: true
