# (C) Crown Copyright 2026, Met Office.
# The LICENSE.md file contains full licensing details.

[command]
default=ln -s $STANDARDISED_DATA_DIR/GCModelDev $ROOT_RESTRUCTURED_DIR

[file:$ROOT_RESTRUCTURED_DIR]
mode=mkdir
