#!/bin/bash -l
# (C) Crown Copyright 2024-2025, Met Office.
# The LICENSE.md file contains full licensing details.
#
# Usage metoffice-standardise-env COMMAND
#
# ENVIRONMENT
#   CDDS_VERSION        The version of CDDS to load
#   PYTHONPATH_PREPEND  The path to prepend to PYTHONPATH after loading the
#                       module
#   QUIET_MODE          Don't print confirmation messages
#
# OPTIONS
#   COMMAND             The command to execute with options
set -eu

# Ensure '~/.local' isn't added to 'sys.path'.
export PYTHONNOUSERSITE=True

# If PYTHONPATH_PREPEND has been set, prepend it to PYTHONPATH to extend the
# Python environment.
if [[ -n ${PYTHONPATH_PREPEND:-} ]]; then
    echo "[INFO] Prepending the following to PYTHONPATH: ${PYTHONPATH_PREPEND}"
    export PYTHONPATH=${PYTHONPATH_PREPEND}:${PYTHONPATH:-}
fi

CDDS_COMMAND="${CDDS_BIN_DIR}/setup_env_for_cdds"
# shellcheck source=/dev/null
source "${CDDS_COMMAND}" "${CDDS_VERSION}"

if [[ -z ${QUIET_MODE:-} ]]; then
    echo "[OK] CDDS environment loaded."
fi

command=(/usr/bin/time -v -o "${CYLC_TASK_LOG_ROOT}.time" "$@")
exec "${command[@]}"
