# (C) Crown Copyright 2026, Met Office.
# The LICENSE.md file contains full licensing details.

[command]
default=cmew-esmvaltool-env install_autoassess.sh

[file:$CYLC_WORKFLOW_SHARE_DIR/src/AutoAssess]
#source=git:localmirrors:MetOffice/AutoAssess.git::./::45_update_for_cmew
# The following commit hash is in the branch above.
source=git:git@github.com:MetOffice/AutoAssess.git::./::5d72106e5740cf468849a1e144a68d5a6254a96c
