# (C) Crown Copyright 2026, Met Office.
# The LICENSE.md file contains full licensing details.

[command]
default=cmew-esmvaltool-env install_package.sh

[env]
SOURCE_DIR = $CYLC_WORKFLOW_SHARE_DIR/src/AutoAssess
TARGET_DIR = $CYLC_WORKFLOW_SHARE_DIR/lib/python
SCRIPT_DIR = $CYLC_WORKFLOW_SHARE_DIR/bin

[file:$CYLC_WORKFLOW_SHARE_DIR/src/AutoAssess]
source=git:localmirrors:MetOffice/AutoAssess.git::./::45_update_for_cmew

[file:$SCRIPT_DIR]
mode=mkdir
