# (C) Crown Copyright 2026, Met Office.
# The LICENSE.md file contains full licensing details.

[command]
default=echo "Installing cmewpy into $CMEW_INSTALL_DIR"

[file:$CMEW_INSTALL_DIR]
source=$CYLC_WORKFLOW_RUN_DIR/cmewpy/cmewpy
