# (C) Crown Copyright 2026, Met Office.
# The LICENSE.md file contains full licensing details.

[file:model_runs.nl]
source=(namelist:model_runs(:))

[namelist:model_runs(experiment)]
other_key="not_needed"
suite_id="line_9"

[namelist:model_runs(2)]
suite_id="line_12"

[namelist:model_runs(reference)]
not_a_suite_id=should_not_copy
suite_id="line_16"

[other variables]
KEY=True
SUITE_ID="wrong case"
