[command]
default=cmew-esmvaltool-env aa_create_nac_plots            \
       = --plot-dir $AUTOASSESS_OUTPUT_DIR/$AREA/nac_plots \
       = --out-dir $AUTOASSESS_OUTPUT_DIR/$AREA            \
       = --area $AREA                                      \
       = --ref-suite-id $REF_SUITE_ID                      \
       = --exp-suite-id $SUITE_ID                          \
       = --ref-desc '$REF_SUITE_TITLE'                     \
       = --exp-desc '$SUITE_TITLE'
