[command]
default=cmew-esmvaltool-env aa_run_area    \
       = --area $AREA                      \
       = --start-date $START_DATE          \
       = --end-date $END_DATE              \
       = --suite-id1 $REF_SUITE_ID         \
       = --suite-id2 $SUITE_ID             \
       = --suite-title1 '$REF_SUITE_TITLE' \
       = --suite-title2 '$SUITE_TITLE'     \
       = --out-dir $AUTOASSESS_OUTPUT_DIR  \
       = --data-dir $AUTOASSESS_DATA_DIR   \
       = --obs-dir $OBS_CLIM_PATH          \
       = --tmp-dir $CYLC_TASK_WORK_DIR     \
       = --ancil-dir $ANCIL_PATH
