# (C) Crown Copyright 2022-2026, Met Office.
# The LICENSE.md file contains full licensing details.

[command]
default=copy_slightly_wrong_areacello_files.py
       =cmew-esmvaltool-env esmvaltool run ${RECIPE_PATH}
