# (C) Crown Copyright 2022-2026, Met Office.
# The LICENSE.md file contains full licensing details.

[command]
default=mkdir -p $CYLC_WORKFLOW_SHARE_DIR/work/GCModelDev/ESMVal/MOHC/HadGEM3-GC31-LL/historical-u-bv526/r5i1p1f3/Ofx/areacello/gn/v20190709
       =cp $HOME/CMEW_related/cell_areas_CMIP6/piControl/r1i1p1f1/Ofx/areacello/gn/v20190709/areacello_Ofx_HadGEM3-GC31-LL_piControl_r1i1p1f1_gn.nc $CYLC_WORKFLOW_SHARE_DIR/work/GCModelDev/ESMVal/MOHC/HadGEM3-GC31-LL/historical-u-bv526/r5i1p1f3/Ofx/areacello/gn/v20190709/areacello_Ofx_HadGEM3-GC31-LL_historical-u-bv526_r5i1p1f3_gn.nc
       =cmew-esmvaltool-env esmvaltool run ${RECIPE_PATH}
