# (C) Crown Copyright 2026, Met Office.
# The LICENSE.md file contains full licensing details.

[command]
default=clone_esmvaltool.sh

[env]
ESMVALTOOL_URL=git@github.com:ESMValGroup/ESMValTool.git

[file:$ESMVALTOOL_DIR]
mode=mkdir
