[command]
default=cmew-esmvaltool-env aa_retriever         \
       = --suite-id $SUITE_ID                    \
       = --area $AREA                            \
       = --start-date $START_DATE                \
       = --end-date $END_DATE                    \
       = --dest-dir $AUTOASSESS_DATA_DIR         \
       = --tmp-dir $CYLC_TASK_WORK_DIR           \
       = --procs 3
