# (C) Crown Copyright 2026, Met Office.
# The LICENSE.md file contains full licensing details.

[command]
default=cmew-esmvaltool-env create_html_page.py \
       = $J2_TEMPLATE_FILE $OUTPUT_FILE

[env]
ASSESSMENT_TITLE=$ASSESSMENT_TITLE
REF_SUITE_ID=$REF_SUITE_ID
SUITE_ID=$SUITE_ID
START_DATE=$START_DATE
END_DATE=$END_DATE
J2_TEMPLATE_FILE=$J2_TEMPLATE_FILE
OUTPUT_FILE=$OUTPUT_FILE
