# (C) Crown Copyright 2026, Met Office.
# The LICENSE.md file contains full licensing details.

[env]
METRIC_DIR=u-cw673_vs_u-bv526/${CYLC_TASK_PARAM_autoassess_area}
METRIC_FILES=nac_plots/monsoon_east_indices.png
            =nac_plots/monsoon_east.png
            =nac_plots/monsoon_south_indices.png
            =nac_plots/monsoon_south.png
            =nac_plots/monsoon_east_other.png
            =nac_plots/monsoon_overview.png
            =nac_plots/monsoon_south_other.png
            =u-bv526/metrics.csv
            =u-cw673/metrics.csv
