# (C) Crown Copyright 2022-2026, Met Office.
# The LICENSE.md file contains full licensing details.

[template variables]
AUTOASSESS=true
AUTOASSESS_TITLE="AUTOASSESS TITLE"
CDDS_VERSION="3.3.3"
ESMVALTOOL_MODULE_NAME="scitools/community/esmvaltool/2.14.0"
MIP_TABLE_DIR="~cdds/etc/mip_tables/GCModelDev/0.0.25"
ROOTPATH_CMIP6="/data/users/managecmip/champ/CMIP6"
ROOTPATH_OBS="/data/users/esmval/ESMValTool/obs"
ROOTPATH_OBS4MIPS="/data/users/esmval/ESMValTool/temporary/obs"
SITE="metoffice"
