# (C) Crown Copyright 2024-2025, Met Office.
# The LICENSE.md file contains full licensing details.

[command]
# The request file depends on information in the variables file,
# so is created second.
default=cmew-esmvaltool-env create_variables_file \
       =--vars_files_list_dir $VARIABLES_LIST_DIR \
       =--stream_config_fp $STREAM_CONFIG_PATH \
       =--output_filepath $VARIABLES_PATH
       =cmew-esmvaltool-env create_request_file \
       =--dataset $CYLC_TASK_PARAM_dataset \
       =--output_filepath $REQUEST_PATH \
       =--defaults_path $REQUEST_DEFAULTS_PATH \
       =--mip_table_dir $MIP_TABLE_DIR \
       =--model_runs_yml_fp ${DATASETS_LIST_DIR}/model_runs.yml \
       =--root_proc_dir $ROOT_PROC_DIR \
       =--root_data_dir $ROOT_DATA_DIR \
       =--variables_file $VARIABLES_PATH \
       =--raw_data_dir_mode $RAW_DATA_DIR_MODE
       =configure_standardise.sh

[file:$CYLC_WORKFLOW_SHARE_DIR/etc]
mode=mkdir
