# (C) Crown Copyright 2026, Met Office.
# The LICENSE.md file contains full licensing details.

[file:model_runs.nl]
source=(namelist:model_runs(:))

[namelist:other_section(1)]
suite_id="shouldn't copy"

[namelist:model_runs(1)]
other_key="not_needed"
suite_id="line_12"

[namelist:model_runs(2)]
suite_id="line_15"

[namelist:model_runs(3)]
suite_id="line_18"
suite_id="duplicated_at_line_19"

[other variables]
KEY=True
SUITE_ID="wrong section"
