# (C) Crown Copyright 2026, Met Office.
# The LICENSE.md file contains full licensing details.

[file:model_runs.nl]
source=(namelist:model_runs(:))

[namelist:other_section(1)]
suite_id="shouldn't copy"

[namelist:model_runs(1)]
other_key="not_needed"
suite_id="line_12"

[namelist:model_runs(2)]
suite_id="line_15"

[namelist:model_runs(3)]
not_a_suite_id=should_not_copy
suite_id="line_19"

[namelist:model_runs(3)]
label=This is a section with a duplicated header
suite_id="from a duplicate"

[other variables]
KEY=True
SUITE_ID="wrong section"
