# (C) Crown Copyright 2024-2026, Met Office.
# The LICENSE.md file contains full licensing details.

[command]
default=set -euo pipefail
       =cmew-standardise-env cdds_convert "${REQUEST_PATH}"
       =save_raw_data.sh
