# (C) Crown Copyright 2024-2026, Met Office.
# The LICENSE.md file contains full licensing details.

[command]
default=set -euo pipefail
       # Select only the last match to avoid selecting any log messages
       # from 'cmew-esmvaltool-env' that may contain the recipe name,
       # e.g. from the 'run_name'.
       =ESMVALTOOL_RECIPE_PATH=$(cmew-esmvaltool-env esmvaltool recipes list | grep $CYLC_TASK_PARAM_recipe | tail -n 1)
       =cmew-esmvaltool-env esmvaltool recipes get $ESMVALTOOL_RECIPE_PATH
       =mv $RECIPE_NAME $RECIPE_PATH
       =cmew-esmvaltool-env update_recipe_file \
       =--recipe_path $RECIPE_PATH \
       =--model_runs_yml_fp ${DATASETS_LIST_DIR}/model_runs.yml \
       =--cmip6_datasets_yml_fp ${DATASETS_LIST_DIR}/cmip6_datasets.yml \
       =--recipe_id $CYLC_TASK_PARAM_recipe \
       =--recipe_dict_fp $RECIPE_DICT_PATH
       =cmew-esmvaltool-env get_variables_from_recipe \
       =--recipe_path $RECIPE_PATH \
       =--output_filepath $RECIPE_VARIABLES_PATH

[file:$VARIABLES_LIST_DIR]
mode=mkdir

[file:${CYLC_WORKFLOW_SHARE_DIR}/etc]
mode=mkdir
