# (C) Crown Copyright 2024-2026, Met Office.
# The LICENSE.md file contains full licensing details.
#
# Select only the last match to avoid selecting any log messages
# from 'cmew-esmvaltool-env' that may contain the recipe name,
# e.g. from the 'run_name'.

[command]
default=set -euo pipefail
       =bash -lc "bash /home/users/jonathan.lillis/Repositories/CMEW/CMEW/app/configure_for/bin/run_update_recipe.sh"

[file:$VARIABLES_LIST_DIR]
mode=mkdir

[file:${CYLC_WORKFLOW_SHARE_DIR}/etc]
mode=mkdir
