# (C) Crown Copyright 2024-2026, Met Office.
# The LICENSE.md file contains full licensing details.

[command]
default=cmew-esmvaltool-env esmvaltool recipes get ${RECIPE_NAME}
       =mv ${RECIPE_NAME} ${RECIPE_PATH}
       =update_recipe_file.py
       =cmew-esmvaltool-env output_variables.py

[file:${CYLC_WORKFLOW_SHARE_DIR}/etc]
mode=mkdir

[file:$VARIABLES_LIST_DIR]
mode=mkdir
